import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  breakingNews: [
    'Results Expected Next Week',
    'New Tourism Package for Nellore Beach Destinations Launched',
    'Local Sports Team Qualifies for National Tournament',
    'APPSC Group 2 Main Examination Schedule Announced',
  ],
  jobs: [],
  govtJobs: [
    {
      id: 1,
      title: 'Junior Assistant',
      company: 'AP District Court',
      location: 'Nellore',
      postedDate: 'Posted Today',
      description: 'Clerical support for case records, data entry, front-desk assistance.',
      buttonType: 'apply',
    },
    {
      id: 2,
      title: 'Village Revenue Officer',
      company: 'Revenue Dept',
      location: 'Naidupeta',
      postedDate: '2d ago',
      description: 'Assist surveys, land records, grievance redressal at mandal level.',
      buttonType: 'view',
    },
    {
      id: 3,
      title: 'Staff Nurse (District Hospital)',
      company: 'Health Dept',
      location: 'Kavali',
      postedDate: '1d ago',
      description: 'Provide patient care, ward coordination, and basic diagnostics.',
      buttonType: 'apply',
    },
    {
      id: 4,
      title: 'Assistant Engineer (Civil)',
      company: 'R&B Dept',
      location: 'Nellore',
      postedDate: '5d ago',
      description: 'Site supervision, BOQ prep, and vendor coordination.',
      buttonType: 'view',
    },
  ],
  privateJobs: [
    {
      id: 5,
      title: 'Logistics Executive',
      company: 'Krishnapatnam Port',
      location: 'Gudur',
      postedDate: '3+ yrs',
      description: 'Coordinate yard operations, vendor communication, and MIS reporting.',
      buttonType: 'apply',
    },
    {
      id: 6,
      title: 'IT Support Engineer',
      company: 'Regional HQ',
      location: 'Nellore',
      postedDate: 'Fresher',
      description: 'Install and troubleshoot systems, respond to tickets, on-site support.',
      buttonType: 'view',
    },
    {
      id: 7,
      title: 'Sales Associate (Retail)',
      company: 'ElectroMart',
      location: 'Nellore',
      postedDate: 'Full-time',
      description: 'Assist customers, manage billing, and stock shelves.',
      buttonType: 'apply',
    },
    {
      id: 8,
      title: 'QA Analyst',
      company: 'Food Processing Unit',
      location: 'Gudur',
      postedDate: '1-3 yrs',
      description: 'Conduct lab tests, maintain QA logs, ensure compliance.',
      buttonType: 'view',
    },
  ],
  internships: [
    {
      id: 9,
      title: 'Marketing Intern',
      company: 'Local Tourism Board',
      location: '',
      postedDate: '6 weeks',
      description: 'Assist campaigns, content calendars, and partner outreach.',
      buttonType: 'apply',
    },
    {
      id: 10,
      title: 'GIS Intern',
      company: 'Urban Planning Cell',
      location: '',
      postedDate: '8 weeks',
      description: 'Map civic assets and create simple dashboards for field teams.',
      buttonType: 'view',
    },
    {
      id: 11,
      title: 'Content Intern (Travel)',
      company: 'Nelloriens Studio',
      location: '',
      postedDate: '8 weeks',
      description: 'Create reels and guides about local attractions and food.',
      buttonType: 'apply',
    },
    {
      id: 12,
      title: 'Data Entry Intern',
      company: 'Civic Records Cell',
      location: '',
      postedDate: '4 weeks',
      description: 'Digitize forms, maintain spreadsheets, basic QC.',
      buttonType: 'view',
    },
  ],
  updatesFeedItems: [
    {
      id: 1,
      title: 'AP Fisheries Dept: Field Assistant openings',
      category: 'Jobs',
      icon: 'bi-briefcase',
      timeLabel: '2 hrs ago',
      timeframe: 'Last 7 days',
      location: 'Nellore',
      scope: 'District',
      description: 'Applications open until Nov 12. 50 vacancies. Diploma preferred.',
      primaryAction: 'View',
      secondaryAction: 'Save',
      updatedAt: 9,
      engagementScore: 72,
      detail: {
        postedOn: 'Oct 27 2025',
        meta: [
          { label: 'Category', value: 'Jobs' },
          { label: 'Location', value: 'Nellore' },
          { label: 'Last date', value: 'Nov 12' },
        ],
        highlights: [
          'Eligibility: Diploma / ITI. Age 18–32.',
          'Documents: Aadhaar, certificates, photos.',
          'Apply at district office or via online portal.',
        ],
      },
    },
    {
      id: 2,
      title: 'Rain alert: Schools to function till noon',
      category: 'News',
      icon: 'bi-newspaper',
      timeLabel: '4 hrs ago',
      timeframe: 'Today',
      location: 'District',
      scope: 'District',
      description: 'IMD issues yellow alert for coastal AP. Commute with caution.',
      primaryAction: 'Read',
      secondaryAction: 'Share',
      updatedAt: 8,
      engagementScore: 64,
      detail: {
        postedOn: 'Oct 27 2025',
        meta: [
          { label: 'Issued by', value: 'IMD' },
          { label: 'Alert', value: 'Yellow' },
          { label: 'Coverage', value: 'Entire district' },
        ],
        highlights: [
          'Morning schools operate till noon as precaution.',
          'Commuters advised to avoid peak-hour travel.',
          'Fishermen cautioned against venturing far from shore.',
        ],
      },
    },
    {
      id: 3,
      title: 'Polytechnic Results: Revaluation dates released',
      category: 'Results',
      icon: 'bi-mortarboard',
      timeLabel: 'Today',
      timeframe: 'Today',
      location: 'State',
      scope: 'State',
      description: 'Revaluation window from Oct 29 to Nov 2. Help desks available.',
      primaryAction: 'Check',
      secondaryAction: 'Download',
      updatedAt: 10,
      engagementScore: 81,
      detail: {
        postedOn: 'Oct 27 2025',
        meta: [
          { label: 'Window', value: 'Oct 29 - Nov 2' },
          { label: 'Fee', value: '₹500 per paper' },
          { label: 'Support', value: 'Help desks @ polytechnic colleges' },
        ],
        highlights: [
          'Use hall-ticket number to apply online.',
          'Original mark sheet mandatory for submission.',
          'Results expected within 15 days after window closes.',
        ],
      },
    },
    {
      id: 4,
      title: 'Tourism: Weekend heritage walk slots added',
      category: 'Tourism',
      icon: 'bi-globe',
      timeLabel: '17 hrs ago',
      timeframe: 'Last 7 days',
      location: 'Nellore Fort',
      scope: 'City',
      description: 'Extra 30 slots available for Saturday evening walk.',
      primaryAction: 'Book',
      secondaryAction: 'Itinerary',
      updatedAt: 6,
      engagementScore: 55,
      detail: {
        postedOn: 'Oct 26 2025',
        meta: [
          { label: 'Slots', value: '30 added' },
          { label: 'Timing', value: 'Saturday, 5 PM' },
          { label: 'Guide', value: 'Local historians' },
        ],
        highlights: [
          'Includes complimentary audio device.',
          'Assemble at fort entrance 15 mins prior.',
          'Family-friendly with wheelchair support.',
        ],
      },
    },
    {
      id: 5,
      title: 'Traffic advisory: One-way trial near Pogathota',
      category: 'News',
      icon: 'bi-megaphone',
      timeLabel: 'Today',
      timeframe: 'Today',
      location: 'City',
      scope: 'City',
      description: 'Diversions between 6-9 PM. Expect delays on trunk road.',
      primaryAction: 'Map',
      secondaryAction: 'Remind',
      updatedAt: 7,
      engagementScore: 60,
      detail: {
        postedOn: 'Oct 28 2025',
        meta: [
          { label: 'Duration', value: '6-9 PM' },
          { label: 'Stretch', value: 'Pogathota main road' },
          { label: 'Contact', value: 'Traffic helpline 100' },
        ],
        highlights: [
          'One-way pilot to ease evening congestion.',
          'Use alternate routes via Magunta Layout.',
          'Public transport frequency increased during trial.',
        ],
      },
    },
    {
      id: 6,
      title: 'Krishnapatnam Port: Night operations expanded',
      category: 'Jobs',
      icon: 'bi-briefcase',
      timeLabel: '18 min ago',
      timeframe: 'Today',
      location: 'Harbor',
      scope: 'Regional',
      description: 'Additional berths open 10 PM–5 AM to ease cargo movement.',
      primaryAction: 'Open',
      secondaryAction: 'Follow',
      updatedAt: 11,
      engagementScore: 78,
      detail: {
        postedOn: 'Oct 29 2025',
        meta: [
          { label: 'Shift', value: '10 PM – 5 AM' },
          { label: 'Berths', value: '2 extra' },
          { label: 'Ops', value: 'Bulk + container' },
        ],
        highlights: [
          'Additional staffing requirements announced internally.',
          'Helpline available for fleet scheduling support.',
          'Goal: reduce average vessel wait time by 40 minutes.',
        ],
      },
    },
  ],
  updateCategoryTabs: [
    { label: 'All', icon: 'bi-bell' },
    { label: 'Jobs', icon: 'bi-briefcase' },
    { label: 'News', icon: 'bi-newspaper' },
    { label: 'Results', icon: 'bi-mortarboard' },
    { label: 'Tourism', icon: 'bi-globe' },
  ],
  updatesFilterOptions: {
    category: ['All', 'Jobs', 'News', 'Results', 'Tourism'],
    time: ['Last 7 days', 'Today', 'Last 30 days', 'All time'],
    location: ['Global', 'Regional', 'State', 'District', 'City'],
    sort: ['Recent', 'Popular'],
  },
  updatesQuickLinks: [
  { id: 1, icon: 'bi-briefcase', label: 'Latest Govt Jobs' },
  { id: 2, icon: 'bi-mortarboard', label: 'Exam Results & Schedules' },
  { id: 3, icon: 'bi-newspaper', label: 'Top News Today' },
  { id: 4, icon: 'bi-globe', label: 'Tourism Guides' },
  ],
  updatesTrendingTags: ['#nellore', '#jobs', '#results', '#traffic', '#tourism'],
  updatesSavedItems: [
    { id: 1, label: 'Scholarship applications open' },
    { id: 2, label: 'Heritage walk slots added' },
    { id: 3, label: 'Traffic advisory tonight' },
  ],
  updatesPaginationInfo: {
    current: 1,
    total: 14,
  },
  updatesStatusIndicators: [
    { id: 1, icon: 'bi-bell', label: 'Real-time feed enabled' },
    { id: 2, icon: 'bi-chat-right', label: 'Community comments open' },
    { id: 3, icon: 'bi-bookmark-check', label: 'Saved updates visible' },
  ],
  jobsPage: {
    currentPage: 1,
    totalPages: 32,
    isLoading: false,
  },
  newsFeedFilters: [
    { id: 'All', label: 'All' },
    { id: 'local', label: 'Local', icon: 'bi-house-door' },
    { id: 'tourism', label: 'Tourism', icon: 'bi-sun' },
    { id: 'international', label: 'International', icon: 'bi-globe2' },
  ],
  newsFeedArticles: [
    {
      id: 1,
      title: 'Coastal cleanup drive this Sunday',
      categoryLabel: 'Local',
      time: '2 hrs ago',
      filterCategory: 'local',
      image:
        'https://images.unsplash.com/photo-1489515217757-5fd1be406fef?w=800&h=500&fit=crop',
    },
    {
      id: 2,
      title: 'New flight routes to Chennai & Hyderabad',
      categoryLabel: 'Travel',
      time: '4 hrs ago',
      filterCategory: 'local',
      image:
        'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&h=500&fit=crop',
    },
    {
      id: 3,
      title: 'Markets rally after policy update',
      categoryLabel: 'International',
      time: 'Today',
      filterCategory: 'international',
      image:
        'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&h=500&fit=crop',
    },
    {
      id: 4,
      title: 'Port throughput hits monthly record',
      categoryLabel: 'Business',
      time: '1 hr ago',
      filterCategory: 'international',
      image:
        'https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=800&h=500&fit=crop',
    },
    {
      id: 5,
      title: 'Intermittent showers across district',
      categoryLabel: 'Weather',
      time: 'Today',
      filterCategory: 'local',
      image:
        'https://images.unsplash.com/photo-1501696461415-6bd6660c6742?w=800&h=500&fit=crop',
    },
    {
      id: 6,
      title: 'State volleyball qualifiers announced',
      categoryLabel: 'Sports',
      time: '3 hrs ago',
      filterCategory: 'international',
      image:
        'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&h=500&fit=crop',
    },
    {
      id: 7,
      title: 'Polytechnic results: help desks set up',
      categoryLabel: 'Education',
      time: '5 hrs ago',
      filterCategory: 'tourism',
      image:
        'https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?w=800&h=500&fit=crop',
    },
    {
      id: 8,
      title: 'Peak-hour traffic diversions tonight',
      categoryLabel: 'Traffic',
      time: 'Tonight',
      filterCategory: 'tourism',
      image:
        'https://images.unsplash.com/photo-1503785640985-f62e9378a7b6?w=800&h=500&fit=crop',
    },
    {
      id: 9,
      title: 'Cultural fest lineup released',
      categoryLabel: 'Events',
      time: 'This Week',
      filterCategory: 'tourism',
      image:
        'https://images.unsplash.com/photo-1470229538611-16ba8c7ffbd7?w=800&h=500&fit=crop',
    },
  ],
  newsPage: {
    currentPage: 2,
    totalPages: 32,
    isLoading: false,
  },
  featuredArticle: {
    id: 1,
    title: 'Port throughput hits monthly record',
    publishedDate: '27 Oct 2025',
    image: 'https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=1200&h=600&fit=crop',
    summary: 'Record cargo movement reported at Krishnapatnam Port driven by agri and mineral exports. Officials project steady growth into next quarter.',
  },
  liveNewsFeed: [
    {
      id: 1,
      title: 'Breaking: Heavy rainfall alert issued for coastal AP',
      category: 'Weather',
      time: '5 min ago',
      image: 'https://images.unsplash.com/photo-1501696461415-6bd6660c6742?w=400&h=250&fit=crop',
      actions: ['Open', 'Share'],
    },
    {
      id: 2,
      title: 'Krishnapatnam Port expands night operations',
      category: 'Business',
      time: '18 min ago',
      image: 'https://images.unsplash.com/photo-1508193638397-1c4234db14d8?w=400&h=250&fit=crop',
      actions: ['Open', 'Save'],
    },
    {
      id: 3,
      title: 'Traffic eased after new one-way at Pogathota',
      category: 'Local',
      time: '32 min ago',
      image: 'https://images.unsplash.com/photo-1503785640985-f62e9378a7b6?w=400&h=250&fit=crop',
      actions: ['Open', 'Discuss'],
    },
    {
      id: 4,
      title: 'Scholarship applications open for PG students',
      category: 'Education',
      time: '45 min ago',
      image: 'https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?w=400&h=250&fit=crop',
      actions: ['Open', 'Source'],
    },
  ],
  headlines: {
    list: [
      'AP Tourism adds weekend heritage walks',
      'City hospital inaugurates cardiac wing',
      'Fish prices dip after bumper catch',
    ],
    items: [
      {
        id: 1,
        title: 'District T20 trials on Nov 3',
        category: 'Sports',
        time: 'Today',
        image: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=400&h=250&fit=crop',
      },
      {
        id: 2,
        title: 'Temple fest traffic advisory',
        category: 'Advisory',
        time: '1 hr ago',
        image: 'https://images.unsplash.com/photo-1470229538611-16ba8c7ffbd7?w=400&h=250&fit=crop',
      },
    ],
  },
  liveNewsCount: 4,
  newsItems: [
    {
      id: 1,
      title: 'City to host coastal cleanup drive',
      subtitle: '2 hrs ago',
      icon: 'bi-broadcast',
      badge: 'Nellore',
      badgeColor: 'light-blue',
    },
    {
      id: 2,
      title: 'National Games: State clinches 3 golds',
      subtitle: 'Featured - 2h',
      icon: 'bi-trophy',
      badge: 'Sports',
      badgeColor: 'light-blue',
    },
  ],
  publicInfo: [
    {
      id: 1,
      title: 'Power shutdown schedule (Nov 29)',
      subtitle: 'DISCOM',
      icon: 'bi-bell',
      badge: 'Notice',
      badgeColor: 'light-blue',
    },
    {
      id: 2,
      title: 'Light showers across district',
      subtitle: 'IMD',
      icon: 'bi-cloud-rain',
      badge: 'Weather',
      badgeColor: 'light-blue',
    },
  ],
  events: [
    {
      id: 1,
      title: 'Tourism Festival Opening Night',
      subtitle: 'Friday - Beach Road',
      icon: 'bi-calendar-event',
      badge: 'Free',
      badgeColor: 'light-blue',
    },
    {
      id: 2,
      title: 'Folk Music Evening',
      subtitle: 'Saturday - Town Hall',
      icon: 'bi-music-note-beamed',
      badge: 'Cultural',
      badgeColor: 'light-blue',
    },
  ],
  results: [
    {
      id: 1,
      title: 'APPSC Group-4 provisional list',
      subtitle: 'Download PDF',
      icon: 'bi-file-earmark-text',
      badge: 'Official',
      badgeColor: 'light-blue',
    },
    {
      id: 2,
      title: 'Polytechnic semester results',
      subtitle: 'Check roll no.',
      icon: 'bi-mortarboard',
      badge: 'Academic',
      badgeColor: 'light-blue',
    },
  ],
  sports: [
    {
      id: 1,
      title: 'State wins 3 golds in athletics',
      subtitle: '2h ago - Featured',
      icon: 'bi-clock',
      badge: 'Read',
      badgeColor: 'light-blue',
    },
    {
      id: 2,
      title: 'School cricket league new format',
      subtitle: 'Yesterday',
      icon: 'bi-bookmark',
      badge: 'Update',
      badgeColor: 'light-blue',
    },
  ],
  foods: [
    {
      id: 1,
      title: 'Nellore Chepala Pulusu',
      subtitle: 'Traditional fish curry',
      icon: 'bi-egg-fried',
      badge: 'Local',
      badgeColor: 'light-blue',
    },
    {
      id: 2,
      title: 'Ghee Dosa (Ghee Dosa Town)',
      subtitle: 'Famous street food',
      icon: 'bi-cup-hot',
      badge: 'Popular',
      badgeColor: 'light-blue',
    },
  ],
  history: [
    {
      id: 1,
      title: 'Origins of Simhapuri',
      subtitle: 'From ancient trade to modern hub',
      icon: 'bi-building',
      badge: 'Read',
      badgeColor: 'light-blue',
    },
    {
      id: 2,
      title: 'Udayagiri Fort timeline',
      subtitle: 'Key rulers & events',
      icon: 'bi-castle',
      badge: 'Archive',
      badgeColor: 'light-blue',
    },
  ],
  famousstay: [
    {
      id: 1,
      title: 'Seaside Resort - Mypadu',
      subtitle: 'Family friendly - Beachfront',
      icon: 'bi-house-door',
      badge: 'Stay',
      badgeColor: 'light-blue',
    },
    {
      id: 2,
      title: 'Business Hotel - City Center',
      subtitle: 'Near transport hub',
      icon: 'bi-building',
      badge: 'Business',
      badgeColor: 'light-blue',
    },
  ],
  offers: [
    {
      id: 1,
      title: 'Restaurant Week: Flat 20% off',
      subtitle: 'Across select eateries',
      icon: 'bi-percent',
      badge: 'Limited',
      badgeColor: 'light-blue',
    },
    {
      id: 2,
      title: 'Bus Pass Discounts',
      subtitle: 'Students & seniors',
      icon: 'bi-bus',
      badge: 'Save',
      badgeColor: 'light-blue',
    },
  ],
  newsLines: [
    { id: 1, text: 'Heavy traffic near Magunta Layout; expect delays', icon: 'bi-lightning' },
    { id: 2, text: 'Water maintenance 10am-2pm in Ward 5', icon: 'bi-droplet' },
    { id: 3, text: 'State-level volleyball trials on Saturday', icon: 'bi-volleyball' },
  ],
  sponsored: [
    {
      id: 1,
      image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&h=250&fit=crop',
      title: 'Explore Maldives & Sri Lanka',
      subtitle: 'Curated packages from Chennai',
      buttonText: 'Book Now',
      buttonColor: 'blue',
    },
    {
      id: 2,
      image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=250&fit=crop',
      title: 'Nellore Meals Festival',
      subtitle: '20% off this week',
      buttonText: 'Visit',
      buttonColor: 'gray',
    },
  ],
  commonAds: [
    {
      id: 1,
      image: 'https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=400&h=250&fit=crop',
      title: 'Festival Electronics Sale',
      buttonText: 'Shop',
      buttonColor: 'blue',
    },
    {
      id: 2,
      image: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=400&h=250&fit=crop',
      title: 'Coaching Admissions Open',
      buttonText: 'Enroll',
      buttonColor: 'gray',
    },
  ],
  updates: [],
};

const newsSlice = createSlice({
  name: 'news',
  initialState,
  reducers: {
    addNews: (state, action) => {
      state.newsItems.push(action.payload);
    },
    addJob: (state, action) => {
      state.jobs.push(action.payload);
    },
    addEvent: (state, action) => {
      state.events.push(action.payload);
    },
    addUpdate: (state, action) => {
      state.updates.push(action.payload);
    },
    setNewsPage: (state, action) => {
      state.newsPage.currentPage = action.payload;
    },
    setNewsLoading: (state, action) => {
      state.newsPage.isLoading = action.payload;
    },
    setJobsPage: (state, action) => {
      state.jobsPage.currentPage = action.payload;
    },
    setJobsLoading: (state, action) => {
      state.jobsPage.isLoading = action.payload;
    },
  },
});

export const { 
  addNews, 
  addJob, 
  addEvent, 
  addUpdate, 
  setNewsPage,
  setNewsLoading,
  setJobsPage, 
  setJobsLoading 
} = newsSlice.actions;
export default newsSlice.reducer;

